#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#ifndef APP_LOGGING_ENABLED
#define APP_LOGGING_ENABLED 1
#endif //APP_LOGGING_ENABLED

#ifndef APP_HID_ENABLED
#define APP_HID_ENABLED 1
#endif //APP_HID_ENABLED

#ifndef APP_BLE_ENABLED
#define APP_BLE_ENABLED 0
#endif //APP_BLE_ENABLED

#ifndef APP_NFC_ENABLED
#define APP_NFC_ENABLED 0
#endif //APP_NFC_ENABLED

#ifndef ENABLE_U2F
#define ENABLE_U2F
#endif //ENABLE_U2F


#define KEY_SPACE_BYTES     96
#define MAX_KEYS            (8)
#define PIN_SALT_LEN        (32)
#define STATE_VERSION        (1)


/******************SDK CONFIG OVERWRITE********/

/* LOG */

// settings
#define NRF_LOG_ENABLED 1
#define NRF_LOG_DEFERRED 1
#define NRF_LOG_USES_COLORS 1 
#ifdef DEBUG
    #define NRF_LOG_DEFAULT_LEVEL 4
#else
    #define NRF_LOG_DEFAULT_LEVEL 2
#endif

//module logging
#define USBD_CONFIG_LOG_ENABLED 0
#define USBD_CONFIG_LOG_LEVEL 4
#define NRFX_USBD_CONFIG_LOG_ENABLED 0
#define NRFX_USBD_CONFIG_LOG_LEVEL 4
#define APP_USBD_CONFIG_LOG_ENABLED 0
#define APP_USBD_CONFIG_LOG_LEVEL 4
#define	MEM_MANAGER_CONFIG_LOG_ENABLED 0
//#define MEM_MANAGER_ENABLE_DIAGNOSTICS 0
#define	MEM_MANAGER_CONFIG_LOG_LEVEL 4 


// backend
#define NRF_LOG_BACKEND_UART_ENABLED 1
#define NRF_LOG_BACKEND_UART_TX_PIN 20
#define NRF_LOG_BACKEND_UART_BAUDRATE 30801920
#define NRF_LOG_BACKEND_UART_TEMP_BUFFER_SIZE 64


/* UART CONFIG */
#define NRFX_UART_ENABLED 0
#define NRFX_UARTE_ENABLED 1
#define NRFX_UARTE0_ENABLED 1
#define NRFX_UARTE1_ENABLED 0


/* TIMER */
#define NRFX_TIMER_ENABLED 1
#define NRFX_TIMER0_ENABLED 1
#define NRFX_TIMER1_ENABLED 1
//#define NRFX_TIMER2_ENABLED 1
//#define NRFX_TIMER3_ENABLED 1
//#define NRFX_TIMER4_ENABLED 1
#define APP_TIMER_KEEPS_RTC_ACTIVE 1
#define RTC_ENABLED 1
#define RTC1_ENABLED 1
#define RTC_DEFAULT_CONFIG_RELIABLE 1
//#define NRFX_RTC_ENABLED 1
//#define NRFX_RTC1_ENABLED 1


/* softdevice */
#define NRF_SDH_ENABLED 1
#define NRF_SDH_SOC_ENABLED 1


/* FDS */
#define FDS_ENABLED 1
#define FDS_BACKEND 2
#define FDS_VIRTUAL_PAGES 8
#define FDS_CRC_CHECK_ON_READ 0
#define FDS_CRC_CHECK_ON_WRITE 0
#define CRC16_ENABLED 0
#define FDS_OP_QUEUE_SIZE 20
#define APP_SCHEDULER_ENABLED 1
// probably wrong
//#define DFU_APP_DATA_RESERVED 1


/* FSTORAGE */
#define NRF_FSTORAGE_ENABLED 1


/* CRYPTO */
#define NRF_CRYPTO_ENABLED 1

// BACKENDS
#define NRF_CRYPTO_BACKEND_CC310_ENABLED 1
#define NRF_CRYPTO_BACKEND_CIFRA_ENABLED 1
#define NRF_CRYPTO_BACKEND_MBEDTLS_ENABLED 1
#define NRF_CRYPTO_BACKEND_MICRO_ECC_ENABLED 1

// CC310
#define NRF_CRYPTO_BACKEND_CC310_CHACHA_POLY_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_AES_CBC_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_AES_CTR_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_AES_ECB_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_AES_CBC_MAC_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_AES_CMAC_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_AES_CCM_STAR_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP160R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP160R2_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP192R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP224R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP256R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP384R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP521R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP160K1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP192K1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP224K1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_SECP256K1_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_CURVE25519_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_ECC_ED25519_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_HASH_SHA256_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_HASH_SHA512_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_HMAC_SHA256_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_HMAC_SHA512_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_RNG_ENABLED 0
#define NRF_CRYPTO_BACKEND_CC310_INTERRUPTS_ENABLED 1

// MBED
#define NRF_CRYPTO_BACKEND_MBEDTLS_AES_CTR_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_AES_CFB_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_AES_ECB_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_AES_CBC_MAC_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_AES_CMAC_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_AES_CCM_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_AES_GCM_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_SECP192R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_SECP224R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_SECP256R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_SECP384R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_SECP521R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_SECP192K1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_SECP224K1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_SECP256K1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_BP256R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_BP384R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_BP512R1_ENABLED 0
#define NRF_CRYPTO_BACKEND_MBEDTLS_ECC_CURVE25519_ENABLED 0

// RNG
#define RNG_ENABLED 1
#define NRFX_RNG_ENABLED 1
#define NRF_CRYPTO_BACKEND_NRF_HW_RNG_ENABLED 1
#define NRF_CRYPTO_RNG_STATIC_MEMORY_BUFFERS_ENABLED 1
#define NRF_CRYPTO_RNG_AUTO_INIT_ENABLED 1

// HASH
#define NRF_CRYPTO_BACKEND_MBEDTLS_HASH_SHA256_ENABLED 1
#define NRF_CRYPTO_BACKEND_MBEDTLS_HASH_SHA512_ENABLED 1

// HMAC
#define NRF_CRYPTO_BACKEND_MBEDTLS_HMAC_SHA256_ENABLED 1
#define NRF_CRYPTO_BACKEND_MBEDTLS_HMAC_SHA512_ENABLED 1

// ECC

// AES
#define NRF_CRYPTO_BACKEND_MBEDTLS_AES_CBC_ENABLED 1


/* USB */
#define APP_USBD_ENABLED 1
#define APP_USBD_HID_ENABLED 1
#define APP_USBD_HID_GENERIC_ENABLED 1
#define NRFX_USBD_ENABLED 1
#define NRFX_SYSTICK_ENABLED 1

#define APP_USBD_VID 0x1915
#define APP_USBD_PID 0x520F
#define APP_USBD_STRINGS_PRODUCT APP_USBD_STRING_DESC("nRF52 FIDO2 Security Key")
#define APP_USBD_STRING_SERIAL APP_USBD_STRING_DESC("000000000001")


/* mem manage */
#define MEM_MANAGER_ENABLED 1
#define MEMORY_MANAGER_SMALL_BLOCK_COUNT 32
#define MEMORY_MANAGER_SMALL_BLOCK_SIZE 32
#define MEMORY_MANAGER_MEDIUM_BLOCK_COUNT 4
#define MEMORY_MANAGER_MEDIUM_BLOCK_SIZE 256
#define MEMORY_MANAGER_XLARGE_BLOCK_COUNT 8
#define MEMORY_MANAGER_XLARGE_BLOCK_SIZE 3444
#define MEMORY_MANAGER_XXLARGE_BLOCK_COUNT 2
#define MEMORY_MANAGER_XXLARGE_BLOCK_SIZE 4096


/* other */
#define NRF_QUEUE_ENABLED 1
#define APP_TIMER_ENABLED 1
//#define APP_TIMER_CONFIG_OP_QUEUE_SIZE 30
#define BUTTON_ENABLED 1
#define NRF_CLOCK_ENABLED 1
#define NRFX_CLOCK_ENABLED 1
#define APP_GPIOTE_ENABLED 1
#define NRFX_GPIOTE_ENABLED 1
//#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 8
//#define BSP_SIMPLE 1

#define APPLY_OLD_CONFIG_H__ //stop apply_old config from overwriting config

/******************SDK CONFIG OVERWRITE********/

#endif
