#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#ifndef APP_LOGGING_ENABLED
#define APP_LOGGING_ENABLED 0
#endif //APP_LOGGING_ENABLED

#ifndef APP_HID_ENABLED
#define APP_HID_ENABLED 0
#endif //APP_HID_ENABLED

#ifndef APP_BLE_ENABLED
#define APP_BLE_ENABLED 0
#endif //APP_BLE_ENABLED

#ifndef APP_NFC_ENABLED
#define APP_NFC_ENABLED 0
#endif //APP_NFC_ENABLED






/******************SDK CONFIG OVERWRITE********/

/* LOG settings*/
#define NRF_LOG_ENABLED 1
#define NRF_LOG_DEFAULT_LEVEL 4

/* LOG backend */
#define NRF_LOG_BACKEND_UART_ENABLED 1
#define NRF_LOG_BACKEND_UART_TX_PIN 20
#define NRF_LOG_BACKEND_UART_BAUDRATE 30801920
#define NRF_LOG_BACKEND_UART_TEMP_BUFFER_SIZE 64

/* UART CONFIG */
#define NRFX_UART_ENABLED 0
#define NRFX_UARTE_ENABLED 1
#define NRFX_UARTE0_ENABLED 1
#define NRFX_UARTE1_ENABLED 0

/* TIMER */
#define NRFX_TIMER_ENABLED 1
#define NRFX_TIMER0_ENABLED 1
#define NRFX_TIMER1_ENABLED 1
#define NRFX_TIMER2_ENABLED 1
#define NRFX_TIMER3_ENABLED 1
#define NRFX_TIMER4_ENABLED 1


/* other */
#define APP_TIMER_ENABLED 1
//#define APP_TIMER_CONFIG_OP_QUEUE_SIZE 30
#define BUTTON_ENABLED 1
#define NRF_CLOCK_ENABLED 1
#define NRFX_CLOCK_ENABLED 1
#define APP_GPIOTE_ENABLED 1
#define NRFX_GPIOTE_ENABLED 1
//#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 8
//#define BSP_SIMPLE 1

#define APPLY_OLD_CONFIG_H__ //stop apply_old config from overwriting config

/******************SDK CONFIG OVERWRITE********/

#endif
